registry:
  url: http://registry.jz17demo.acntech.no:5000/v2
  repoPrefix: registry.jz17demo.acntech.no:5000

rundeck:
  url: http://jz17demo.acntech.no:4440/
  authToken: T41CSm6JBGgVRySfthwCle7WjCpwRgTh
  todoapp:
    deployJob: 2565996f-06c6-4354-bcfb-5eb2692f401c
    deleteJob: 159481e0-63b2-4b6d-ac63-0c6b470bb2b8
  apiVersion: 18
  timeout: 5000

servers:
  dockerEnvs:
    - jzworker1
    - jzworker2

  jzworker1:
    name: jzworker1
    ip: 146.185.144.177
    baseUrl: http://146.185.144.177
    dockerPort: 4243
    dockerApi: http://146.185.144.177:4243

  jzworker2:
    name: jzworker2
    ip: 188.226.141.228
    baseUrl: http://188.226.141.228
    dockerPort: 4243
    dockerApi: http://188.226.141.228:4243
